angular.module('webapp',[
	'ngRoute',
	'szseui',
	'bizui',
	'BPM.messageDialog',
	'home',
	'monthticket',
	'onceticket',
	'applynew'
	])
.config(['$routeProvider','$httpProvider',function($routeProvider,$httpProvider){
	$routeProvider
		.when('/monthticket',{
			templateUrl:'module/monthticket/views/index.html',
			controller:'monthticketCtrl'
		})
		.when('/onceticket',{
			templateUrl:'module/onceticket/views/index.html',
			controller:'onceticketCtrl'
		})
		.when('/applynew',{
			templateUrl:'module/applynew/views/index.html',
			controller:'applynewCtrl'
		})
		.otherwise({
			templateUrl:'module/home/views/index.html',
			controller:'homeCtrl'
		});
}]);